### ISSUE TITLE
Audio Asset List

### ISSUE THREAD

**Issue by PatCleaver** [HDJKleissen/GGJ_2022#52]

**Comment by PatCleaver** [comment]
- [x] Dog Barks
- [x] Chicken "Packaw"
- [x] Chicken Death
- [x] Pot Break
- [x] Owner Footsteps
- [x] Dog Footsteps(?)
- [x] UI Confirm
- [x] UI Back
- [x] Fixing sound/Fixed Sound/sweeping
- [x] Score dings
- [x] Cut Scene voice
- [x] Cut Scene Drop bags
- [x] Cut Scene "Ahhhuuuuuu?!"
- [x] Repair Ding
- [x] Single boks for mouse enter

**Comment by Pepn** [comment]
- [x] VictorySound
- [x] Voice/Sound for the cutscene/image
